<?php
return array(
    array(
        "phrase" => "[呵呵]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/ac/smilea_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/ac/smilea_thumb.gif",
        "value" => "[呵呵]",
        "picid" => ""
    ),
    array(
        "phrase" => "[嘻嘻]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/0b/tootha_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/0b/tootha_thumb.gif",
        "value" => "[嘻嘻]",
        "picid" => ""
    ),
    array(
        "phrase" => "[哈哈]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6a/laugh.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6a/laugh.gif",
        "value" => "[哈哈]",
        "picid" => ""
    ),
    array(
        "phrase" => "[可爱]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/14/tza_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/14/tza_thumb.gif",
        "value" => "[可爱]",
        "picid" => ""
    ),
    array(
        "phrase" => "[可怜]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/af/kl_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/af/kl_thumb.gif",
        "value" => "[可怜]",
        "picid" => ""
    ),
    array(
        "phrase" => "[挖鼻屎]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/a0/kbsa_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/a0/kbsa_thumb.gif",
        "value" => "[挖鼻屎]",
        "picid" => ""
    ),
    array(
        "phrase" => "[吃惊]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/f4/cj_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/f4/cj_thumb.gif",
        "value" => "[吃惊]",
        "picid" => ""
    ),
    array(
        "phrase" => "[害羞]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6e/shamea_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6e/shamea_thumb.gif",
        "value" => "[害羞]",
        "picid" => ""
    ),
    array(
        "phrase" => "[挤眼]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/c3/zy_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/c3/zy_thumb.gif",
        "value" => "[挤眼]",
        "picid" => ""
    ),
    array(
        "phrase" => "[闭嘴]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/29/bz_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/29/bz_thumb.gif",
        "value" => "[闭嘴]",
        "picid" => ""
    ),
    array(
        "phrase" => "[鄙视]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/71/bs2_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/71/bs2_thumb.gif",
        "value" => "[鄙视]",
        "picid" => ""
    ),
    array(
        "phrase" => "[爱你]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6d/lovea_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6d/lovea_thumb.gif",
        "value" => "[爱你]",
        "picid" => ""
    ),
    array(
        "phrase" => "[泪]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/9d/sada_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/9d/sada_thumb.gif",
        "value" => "[泪]",
        "picid" => ""
    ),
    array(
        "phrase" => "[偷笑]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/19/heia_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/19/heia_thumb.gif",
        "value" => "[偷笑]",
        "picid" => ""
    ),
    array(
        "phrase" => "[亲亲]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/8f/qq_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/8f/qq_thumb.gif",
        "value" => "[亲亲]",
        "picid" => ""
    ),
    array(
        "phrase" => "[生病]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/b6/sb_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/b6/sb_thumb.gif",
        "value" => "[生病]",
        "picid" => ""
    ),
    array(
        "phrase" => "[太开心]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/58/mb_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/58/mb_thumb.gif",
        "value" => "[太开心]",
        "picid" => ""
    ),
    array(
        "phrase" => "[懒得理你]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/17/ldln_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/17/ldln_thumb.gif",
        "value" => "[懒得理你]",
        "picid" => ""
    ),
    array(
        "phrase" => "[右哼哼]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/98/yhh_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/98/yhh_thumb.gif",
        "value" => "[右哼哼]",
        "picid" => ""
    ),
    array(
        "phrase" => "[左哼哼]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6d/zhh_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6d/zhh_thumb.gif",
        "value" => "[左哼哼]",
        "picid" => ""
    ),
    array(
        "phrase" => "[嘘]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/a6/x_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/a6/x_thumb.gif",
        "value" => "[嘘]",
        "picid" => ""
    ),
    array(
        "phrase" => "[衰]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/af/cry.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/af/cry.gif",
        "value" => "[衰]",
        "picid" => ""
    ),
    array(
        "phrase" => "[委屈]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/73/wq_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/73/wq_thumb.gif",
        "value" => "[委屈]",
        "picid" => ""
    ),
    array(
        "phrase" => "[吐]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/9e/t_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/9e/t_thumb.gif",
        "value" => "[吐]",
        "picid" => ""
    ),
    array(
        "phrase" => "[打哈气]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/f3/k_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/f3/k_thumb.gif",
        "value" => "[打哈气]",
        "picid" => ""
    ),
    array(
        "phrase" => "[抱抱]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/27/bba_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/27/bba_thumb.gif",
        "value" => "[抱抱]",
        "picid" => ""
    ),
    array(
        "phrase" => "[怒]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/7c/angrya_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/7c/angrya_thumb.gif",
        "value" => "[怒]",
        "picid" => ""
    ),
    array(
        "phrase" => "[疑问]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/5c/yw_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/5c/yw_thumb.gif",
        "value" => "[疑问]",
        "picid" => ""
    ),
    array(
        "phrase" => "[馋嘴]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/a5/cza_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/a5/cza_thumb.gif",
        "value" => "[馋嘴]",
        "picid" => ""
    ),
    array(
        "phrase" => "[拜拜]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/70/88_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/70/88_thumb.gif",
        "value" => "[拜拜]",
        "picid" => ""
    ),
    array(
        "phrase" => "[思考]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/e9/sk_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/e9/sk_thumb.gif",
        "value" => "[思考]",
        "picid" => ""
    ),
    array(
        "phrase" => "[汗]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/24/sweata_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/24/sweata_thumb.gif",
        "value" => "[汗]",
        "picid" => ""
    ),
    array(
        "phrase" => "[困]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/7f/sleepya_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/7f/sleepya_thumb.gif",
        "value" => "[困]",
        "picid" => ""
    ),
    array(
        "phrase" => "[睡觉]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6b/sleepa_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6b/sleepa_thumb.gif",
        "value" => "[睡觉]",
        "picid" => ""
    ),
    array(
        "phrase" => "[钱]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/90/money_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/90/money_thumb.gif",
        "value" => "[钱]",
        "picid" => ""
    ),
    array(
        "phrase" => "[失望]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/0c/sw_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/0c/sw_thumb.gif",
        "value" => "[失望]",
        "picid" => ""
    ),
    array(
        "phrase" => "[酷]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/40/cool_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/40/cool_thumb.gif",
        "value" => "[酷]",
        "picid" => ""
    ),
    array(
        "phrase" => "[花心]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/8c/hsa_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/8c/hsa_thumb.gif",
        "value" => "[花心]",
        "picid" => ""
    ),
    array(
        "phrase" => "[哼]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/49/hatea_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/49/hatea_thumb.gif",
        "value" => "[哼]",
        "picid" => ""
    ),
    array(
        "phrase" => "[鼓掌]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/36/gza_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/36/gza_thumb.gif",
        "value" => "[鼓掌]",
        "picid" => ""
    ),
    array(
        "phrase" => "[晕]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d9/dizzya_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d9/dizzya_thumb.gif",
        "value" => "[晕]",
        "picid" => ""
    ),
    array(
        "phrase" => "[悲伤]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/1a/bs_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/1a/bs_thumb.gif",
        "value" => "[悲伤]",
        "picid" => ""
    ),
    array(
        "phrase" => "[抓狂]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/62/crazya_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/62/crazya_thumb.gif",
        "value" => "[抓狂]",
        "picid" => ""
    ),
    array(
        "phrase" => "[黑线]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/91/h_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/91/h_thumb.gif",
        "value" => "[黑线]",
        "picid" => ""
    ),
    array(
        "phrase" => "[阴险]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6d/yx_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6d/yx_thumb.gif",
        "value" => "[阴险]",
        "picid" => ""
    ),
    array(
        "phrase" => "[怒骂]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/89/nm_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/89/nm_thumb.gif",
        "value" => "[怒骂]",
        "picid" => ""
    ),
    array(
        "phrase" => "[心]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/40/hearta_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/40/hearta_thumb.gif",
        "value" => "[心]",
        "picid" => ""
    ),
    array(
        "phrase" => "[伤心]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/ea/unheart.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/ea/unheart.gif",
        "value" => "[伤心]",
        "picid" => ""
    ),
    array(
        "phrase" => "[猪头]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/58/pig.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/58/pig.gif",
        "value" => "[猪头]",
        "picid" => ""
    ),
    array(
        "phrase" => "[ok]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d6/ok_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d6/ok_thumb.gif",
        "value" => "[ok]",
        "picid" => ""
    ),
    array(
        "phrase" => "[耶]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d9/ye_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d9/ye_thumb.gif",
        "value" => "[耶]",
        "picid" => ""
    ),
    array(
        "phrase" => "[good]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d8/good_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d8/good_thumb.gif",
        "value" => "[good]",
        "picid" => ""
    ),
    array(
        "phrase" => "[不要]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/c7/no_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/c7/no_thumb.gif",
        "value" => "[不要]",
        "picid" => ""
    ),
    array(
        "phrase" => "[赞]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d0/z2_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d0/z2_thumb.gif",
        "value" => "[赞]",
        "picid" => ""
    ),
    array(
        "phrase" => "[来]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/40/come_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/40/come_thumb.gif",
        "value" => "[来]",
        "picid" => ""
    ),
    array(
        "phrase" => "[弱]",
        "type" => "face",
        "url" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d8/sad_org.gif",
        "hot" => false,
        "common" => true,
        "category" => "",
        "icon" => "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d8/sad_thumb.gif",
        "value" => "[弱]",
        "picid" => ""
    ),
);